import type { Knex } from 'knex';

/**
 * Converts event_shares.visibility_level from VARCHAR(20) + CHECK constraint
 * to a PostgreSQL ENUM type for stronger data integrity.
 *
 * A native ENUM type is enforced at the type-system level in PostgreSQL,
 * preventing invalid values more reliably than a CHECK constraint alone.
 */
export async function up(knex: Knex): Promise<void> {
  // 1. Create the ENUM type (table-scoped name to avoid collisions)
  await knex.raw(`
    CREATE TYPE event_shares_visibility_level AS ENUM ('busy', 'title', 'details')
  `);

  // 2. Drop the existing CHECK constraint generated by Knex's .checkIn()
  //    Dynamically look up the constraint name scoped to the current schema
  //    to avoid cross-schema interference in multi-schema environments.
  await knex.raw(`
    DO $$
    DECLARE
      constraint_name TEXT;
    BEGIN
      FOR constraint_name IN
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        WHERE nsp.nspname = current_schema()
          AND rel.relname = 'event_shares'
          AND con.contype = 'c'
          AND pg_get_constraintdef(con.oid) LIKE '%visibility_level%'
      LOOP
        EXECUTE format('ALTER TABLE event_shares DROP CONSTRAINT %I', constraint_name);
      END LOOP;
    END $$
  `);

  // 3. Alter the column type from VARCHAR(20) to the new ENUM
  await knex.raw(`
    ALTER TABLE event_shares
      ALTER COLUMN visibility_level DROP DEFAULT,
      ALTER COLUMN visibility_level TYPE event_shares_visibility_level
        USING visibility_level::event_shares_visibility_level,
      ALTER COLUMN visibility_level SET DEFAULT 'title'::event_shares_visibility_level
  `);
}

export async function down(knex: Knex): Promise<void> {
  // 1. Revert the column back to VARCHAR(20) with CHECK constraint
  await knex.raw(`
    ALTER TABLE event_shares
      ALTER COLUMN visibility_level DROP DEFAULT,
      ALTER COLUMN visibility_level TYPE VARCHAR(20)
        USING visibility_level::TEXT,
      ALTER COLUMN visibility_level SET DEFAULT 'title'
  `);

  // 2. Re-add the CHECK constraint to match the original migration
  await knex.raw(`
    ALTER TABLE event_shares
      ADD CONSTRAINT event_shares_visibility_level_check
      CHECK (visibility_level IN ('busy', 'title', 'details'))
  `);

  // 3. Drop the ENUM type
  await knex.raw('DROP TYPE IF EXISTS event_shares_visibility_level');
}
